- connect-examples/v2/php_payment/index.html
> HTML IDs are like the highlander

- connect-examples/v2/python_payment/README.md
- connect-examples/v2/python_payment/cgi-bin/process_card.py
- connect-examples/v2/python_payment/index.html
@DanGe42 @longboardcat @StephenBarlow 
The is the processing payment python example. It'd be great to have your guys' review if you have time! Thanks!
> python example

- connect-examples/v2/php_checkout/templates/README.md
- connect-examples/v2/php_checkout/templates/example-curl-helpers.php
I have no idea what I'm doing. This is maybe the 4th time I've tried to do this. Clearly Git hates me =\
> Template corrections/updates

- connect-examples/v2/php_checkout/templates/example-store-config.php
Some of the API fixes from the original push are missing. The API reference is correct in the error message but that actual call wasn't changed.
> Correct API Call (LocationsApi --> LocationApi)

- connect-examples/v2/php_checkout/templates/example-confirm-transaction.php
reported here: https://github.com/square/connect-api-examples/issues/53
> Fix example logic

- connect-examples/v2/rails_payment/Gemfile.lock
Remove potential security vulnerability as warned by github.
> Remove rails security vulnerability

- connect-examples/v2/php_payment/.env
- connect-examples/v2/php_payment/README.md
- connect-examples/v2/php_payment/composer.json
- connect-examples/v2/php_payment/index.php
- connect-examples/v2/php_payment/process-card.php
- connect-examples/v2/php_payment/sqpaymentform.css
- connect-examples/v2/php_payment/sqpaymentform.js
Let me know if anything needs to be updated or changed. Thanks!
> Updated PHP payment example.

- README.md
- templates/README.md
- templates/php/sq_config.php
- templates/web-ui/payment-form/README.md
- templates/web-ui/payment-form/basic/sqpaymentform-basic.css
- templates/web-ui/payment-form/basic/sqpaymentform-basic.html
- templates/web-ui/payment-form/basic/sqpaymentform-basic.js
Adding a template folder and some starter templates based on current setup guides.
> Update README files and submit initial templates

- README.md
- connect-examples/v2/python_payment/README.md
- connect-examples/v2/python_payment/cgi-bin/index.py
- connect-examples/v2/python_payment/cgi-bin/process_card.py
- connect-examples/v2/python_payment/config.ini
- connect-examples/v2/python_payment/sqpaymentform.css
- connect-examples/v2/python_payment/sqpaymentform.js
Not really sure if this is a "good" way to use Python (throwing the whole HTML page in a Python script). I couldn't find an easer way to prevent replacing credentials in multiple places. If preferred, I can bring back "REPLACE_ME" and remove `config.ini`, so that I can move the `index.py` back into `index.html`.
> Sjosey fix python payment

- connect-examples/v1/java/README.md
- connect-examples/v1/java/pom.xml
- connect-examples/v1/java/src/main/java/com/squareup/connectexamples/ItemManager.java
- connect-examples/v1/java/src/main/java/com/squareup/connectexamples/PaymentsReporter.java
Updated libraries, and fixed the ItemManager. Also made the Payment Reporter use the previous year instead of a hard coded year. Let me know if anything should be changed/added.
> Sjosey fix v1 java example

- connect-examples/v1/php/README.md
- connect-examples/v1/php/item-management.php
- connect-examples/v1/php/payments-report.php
Turns out PHP was actually working, just can't test webhooks on localhost. Updated dates and error handling.
> Sjosey fix v1 php

- templates/web-ui/payment-form/basic-digital-wallet/sqpaymentform-basic-head.html
- templates/web-ui/payment-form/basic-digital-wallet/sqpaymentform-basic.css
- templates/web-ui/payment-form/basic-digital-wallet/sqpaymentform-basic.html
- templates/web-ui/payment-form/basic-digital-wallet/sqpaymentform-basic.js
- templates/web-ui/payment-form/basic/sqpaymentform-basic-head.html
- templates/web-ui/payment-form/basic/sqpaymentform-basic.css
- templates/web-ui/payment-form/basic/sqpaymentform-basic.html
- templates/web-ui/payment-form/basic/sqpaymentform-basic.js
Updated css, html, and js with styling from Chris Knight & Alex Jacques
> basic wallet & no-wallet templates updated with modern styling

- templates/web-ui/payment-form/basic-digital-wallet/sqpaymentform-basic.css
- templates/web-ui/payment-form/basic/sqpaymentform-basic.css
- templates/web-ui/payment-form/digital-wallet-only/sqpaymentform-basic.css
Updated height in .css file for payment form
> Bwiseman to make the form fit on the page

- connect-examples/v2/java_payment/pom.xml
- connect-examples/v2/java_payment/src/main/java/com/squareup/connectexamples/ecommerce/Main.java
- connect-examples/v2/java_payment/src/main/resources/templates/charge.html
- connect-examples/v2/java_payment/src/main/resources/templates/error.html
Switches out old SDK for the new SDK in existing connect examples
> Update Java example

- connect-examples/v2/csharp_checkout/Pages/Checkout.cshtml.cs
- connect-examples/v2/csharp_checkout/csharp_checkout.csproj
Update example to use latest .NET SDK
> Upgraded to new SDK

- templates/php/sq_config.php
Updated helper functions to return sandbox or production values base on an optional param whose default value requests sandbox values
> Improved helper functions to return sandbox or production values

- templates/php/sq_config.php
To add useSandbox setter function and global use Sandbox flag. Removed useSandbox arg from all class functions. Fixed references to class fields and functions
> refactor helper class

- connect-examples/v2/node_orders-payments/bin/script/sample-seed-data.json
- connect-examples/v2/node_orders-payments/bin/script/seed-catalog.js
- connect-examples/v2/node_orders-payments/models/catalog-item-variation.js
- connect-examples/v2/node_orders-payments/models/catalog-list.js
- connect-examples/v2/node_orders-payments/models/delivery-pickup-times.js
- connect-examples/v2/node_orders-payments/models/location-info.js
- connect-examples/v2/node_orders-payments/models/order-info.js
- connect-examples/v2/node_orders-payments/public/js/add-delivery-pickup-details.js
- connect-examples/v2/node_orders-payments/public/js/products-page.js
- connect-examples/v2/node_orders-payments/public/js/sq-payment-form.js
- connect-examples/v2/node_orders-payments/routes/checkout.js
- connect-examples/v2/node_orders-payments/routes/index.js
- connect-examples/v2/node_orders-payments/routes/order-confirmation.js
- connect-examples/v2/node_orders-payments/util/square-connect-client.js
Rather than ask you to make a lot of changes on formatting in your PR, this is just a PR of all the formatting changes that I suggest to include with your changes.
> Ran Prettier on files to format them to be more readable

- connect-examples/oauth/node/package-lock.json
- connect-examples/oauth/node/package.json
- connect-examples/oauth/python-aws-chalice/requirements.txt
- connect-examples/v2/node_invoices/package-lock.json
- connect-examples/v2/node_invoices/package.json
- connect-examples/v2/node_subscription/package-lock.json
- connect-examples/v2/node_subscription/package.json
Resolves 5 of the 6 vulnerabilities listed in the Security tab.
> Resolving vulnerabilities.

- connect-examples/v2/csharp_checkout/LICENSE
- connect-examples/v2/csharp_checkout/README.md
- connect-examples/v2/csharp_payment/LICENSE
- connect-examples/v2/csharp_payment/README.md
- connect-examples/v2/java_payment/LICENSE
- connect-examples/v2/java_payment/README.md
- connect-examples/v2/node_invoices/README.md
- connect-examples/v2/node_orders-payments/README.md
- connect-examples/v2/node_payment/LICENSE
- connect-examples/v2/node_payment/README.md
- connect-examples/v2/node_subscription/README.md
- Update copyright to 2021
- Add license file to projects missing license file
> add LICENSE to all projects

- connect-examples/v2/node_orders-payments/package-lock.json
- connect-examples/v2/node_orders-payments/package.json
- connect-examples/v2/node_payment/package-lock.json
- connect-examples/v2/node_payment/package.json
- connect-examples/v2/node_subscription/package-lock.json
- fix vulnerable dependencies
- fix axios dependency issue
> fix vulnerabilities and axios dependency issue

- connect-examples/v2/csharp_checkout/csharp_checkout.csproj
- connect-examples/v2/csharp_payment/sqRazorSample.csproj
- connect-examples/v2/java_payment/README.md
- connect-examples/v2/java_payment/pom.xml
- connect-examples/v2/node_invoices/package-lock.json
- connect-examples/v2/node_invoices/package.json
- connect-examples/v2/node_invoices/routes/invoice.js
- connect-examples/v2/node_orders-payments/models/catalog-item.js
- connect-examples/v2/node_orders-payments/models/order-info.js
- connect-examples/v2/node_orders-payments/package-lock.json
- connect-examples/v2/node_orders-payments/package.json
- connect-examples/v2/node_orders-payments/routes/index.js
- connect-examples/v2/node_orders-payments/views/index.pug
- connect-examples/v2/node_payment/package-lock.json
- connect-examples/v2/node_payment/package.json
- connect-examples/v2/node_payment/routes/index.js
- connect-examples/v2/node_subscription/models/subscription-details-info.js
- connect-examples/v2/node_subscription/package-lock.json
- connect-examples/v2/node_subscription/package.json
- connect-examples/v2/node_subscription/routes/management.js
- connect-examples/v2/node_subscription/views/subscription.pug
- connect-examples/v2/python_payment/requirements.txt
- connect-examples/v2/rails_payment/Gemfile
- connect-examples/v2/rails_payment/Gemfile.lock
* upgrade SDK version for sample apps to the latest released: 10.0.0
* fix any dependency issues and API usage changes
> Upgrade SDK version for sample apps to the latest released: 10.0.0

- connect-examples/v2/node_invoices/routes/invoice.js
remove duplicate accepted payment in node_invoices, replace `bankAccount` with `card`
> remove duplicate accepted payment in node_invoices, replace bankAccount with card

- connect-examples/v2/rails_snippet/.env
- connect-examples/v2/rails_snippet/README.md
- connect-examples/v2/rails_snippet/config/initializers/omniauth.rb
The README and code say `SQUARE_ACCESS_TOKEN`, but it should be application secret.
> Rename ACCESS_TOKEN to APPLICATION_SECRET

- connect-examples/oauth/php/callback.php
- connect-examples/oauth/php/request_token.php
generate random csrf tokens and store in session data for php oauth app
> generate random csrf tokens and store in session data

- connect-examples/v2/php_payment/README.md
- connect-examples/v2/php_payment/public/js/sq-payment-flow.js
- process-payment -> process-payment.php
- update test credit card in README
> Fix incorrect fetch path in php payment and updated readme

- connect-examples/v2/node_gift-cards/public/js/amount-bar.js
- connect-examples/v2/node_gift-cards/public/js/pretty-select-dropdown.js
Using 2 attributes, disable/enable the pay button dynamically without violating existing behaviour
https://user-images.githubusercontent.com/79542071/122605426-a9c3f280-d034-11eb-9272-6426b05bbd50.mov
> dynamically disable the pay button to prevent amount exceeding the max balance

- connect-examples/v2/php_payment/process-payment.php
> Return errors in a format that is readable by the frontend js library

- connect-examples/v2/node_bookings/README.md
This PR updates the README for the bookings sample app with changes made by the content writers team.
> Update README with content writers changes

- connect-examples/oauth/java/README.md
- connect-examples/oauth/node/README.md
- connect-examples/oauth/php/README.md
- connect-examples/oauth/python-aws-chalice/README.md
- connect-examples/oauth/python/README.md
- connect-examples/oauth/ruby/README.md
- connect-examples/v2/csharp_checkout/README.md
- connect-examples/v2/csharp_payment/README.md
- connect-examples/v2/java_catalog/README.md
- connect-examples/v2/java_payment/README.md
- connect-examples/v2/node_bookings/README.md
- connect-examples/v2/node_gift-cards/README.md
- connect-examples/v2/node_invoices/README.md
- connect-examples/v2/node_orders-payments/README.md
- connect-examples/v2/node_payment/README.md
- connect-examples/v2/node_subscription/README.md
- connect-examples/v2/php_checkout/README.md
- connect-examples/v2/php_payment/README.md
- connect-examples/v2/python_payment/README.md
- connect-examples/v2/rails_payment/README.md
- connect-examples/v2/rails_snippet/README.md
Add survey link to sample app READMEs
> Add Delighted feedback link to sample app READMEs

- connect-examples/v2/graphql-sample-app/index.js
- connect-examples/v2/graphql-sample-app/queries.js
Add pagination to GraphQL sample queries. Tested all queries successfully locally
https://graphql.org/learn/pagination/
> Add pagination to GraphQL sample queries

- connect-examples/v2/node_bookings/package-lock.json
noticed `npm i` was timing out
> fix: use npm registry instead of square's

- connect-examples/v2/node_orders-payments/models/catalog-list.js
- connect-examples/v2/node_orders-payments/package-lock.json
- connect-examples/v2/node_orders-payments/package.json
- connect-examples/v2/node_orders-payments/routes/checkout.js
- connect-examples/v2/node_orders-payments/routes/order-confirmation.js
- connect-examples/v2/node_orders-payments/util/square-client.js
- connect-examples/v2/package-lock.json
The payments/order sample app had a few breaking changes related to Loyalty and Catalog APIs. I've fixed it up to use the latest, non-deprecated, methods and fields.
Fixed as part of this PR:
1. Loyalty integration didn't work at all. Now working as expected.
2. Catalog images wouldn't show up. Now showing up as expected.
3. Fixed high severity vulns in packages.
4. Fixed typos and other nits
Video of after:
https://user-images.githubusercontent.com/21358133/214402703-c1d184a7-97a2-4fd7-86a7-f6d027041287.mov
Testing:
Ran app locally
> Fix node payments/order sample app

- connect-examples/v2/graphql-sample-app/README.md
- connect-examples/v2/graphql-sample-app/index.js
- connect-examples/v2/graphql-sample-app/package-lock.json
- connect-examples/v2/graphql-sample-app/queries.js
We just released GraphQL beta in June 2023, which resulted in broken sample queries in this repo. This is the fix.
> [GQL] Fix broken and outdated GraphQL queries
