square/connect-api-examples

connect-examples/oauth/ruby/oauth-flow.rb

+ Use constants instead of global variables
+ `has_key?` was deprecated in favor of `key?`
+ Removed tab spacing/trailing whitespace
+ Fixed parameter alignment in Unirest.post
Unirest could probably be removed in favor of net/http, which is included in the standard lib.
By the way, there's actually an Omniauth adapter for Square Connect. Omniauth is an OAuth library for Ruby. The adapter can be found here: https://github.com/danieljacobarcher/omniauth-square. I've used it with great success. Perhaps, it's worthy of a mention in the README.

Petty Ruby style updates

---

connect-examples/v2/node_payment/README.rdoc
connect-examples/v2/node_payment/routes/index.js

Previously if you tried use the sample with just your sandbox credentials, you would get an error that the location was not enabled for card processing. This is because the sample would process the payment at the first location returned by the API, which for the sandbox environment doesn't have credit card processing enabled. 
Now the sample will process at the first location that has processing enabled, and throw an error if it can't find one. Additionally the instructions have been updated to tell you where point your browser to actually see the sample.

Update node sample to work with Sandbox credentials

---

connect-examples/v2/php_checkout/templates/example-confirm-transaction.php

Some of the API fixes from the original push are missing. The API reference is incorrect in both the error message and the actual call.

Correct API Call (TransactionsApi --> TransactionApi)

---

connect-examples/v2/php_payment/process-card.php

`empty()` supports expressions since PHP 5.5. Before that, it only
supports variables[1]. Our example didn't work with PHP versions prior
5.5.
[1] http://ca2.php.net/empty

[PHP payment] Fixes how locations are filter for PHP < 5.5

---

templates/web-ui/payment-form/basic/sqpaymentform-basic.js

The form.recalculateSize() should not be called before `paymentFormLoaded` callback.

remove  form.recalculateSize() from template.

---

templates/php/sq_config.php

When including this file, on PHP 7.3.12 at least, you get 6 warnings like:
> PHP Warning:  Use of undefined constant _SQ_SANDBOX_TOKEN - assumed '_SQ_SANDBOX_TOKEN' (this will throw an Error in a future version of PHP)
This is because defined() takes a string not a symbol https://www.php.net/defined

Fix use of defined() in sq_config.php

---

templates/php/sq_config.php

Per feedback, the `require` line is needed regardless of whether the Connect SDK is installed manually or with a package manager.

Moved require statement to top of file and uncommented

---

templates/php/sq_config.php

Developer must be able to store their Square Sandbox environment application secret as a define if they want to test OAuth in the Sandbox environment.

Added a define for an app secret for the sandbox environment

---

templates/php/sq_config.php

The getToken helper function was modified to remove the single parameter.  There were 2 calls to the function that still passed the removed boolean.

Removed argument from getToken() call

---

connect-examples/v2/python_payment/README.md
connect-examples/v2/python_payment/cgi-bin/index.py
connect-examples/v2/python_payment/cgi-bin/process_card.py

I consulted with @hukid over Slack before making these changes. 
Summary:
* `-m CGIHTTPServer` → `-m http.server --cgi` in python3.
* casing of `ConfigParser` is all lower in python3.
* The example CC test fixture is out of date.

updates v2/python_payment for strict python3

---

connect-examples/v2/node_invoices/routes/invoice.js

Remove the confusing useless extra location_id from the request body.

remove unnecessary "location_id" in createOrder call.

---

connect-examples/v2/rails_payment/README.md

The `db:migrate` command isn't available because `rails/all` is commented out, removing it from the README

remove db:migrate command from README

---

connect-examples/v2/rails_payment/Gemfile.lock

The current locked version of mimemagic has been revoked, update the mimemagic version to the latest supported version to unblock `npm build`.

bump and lock mimemagic version

---

connect-examples/v2/python_payment/README.md

Remove python 2.7 support from README as it has been EOLed for a while

remove python 2.7 support from README as it has been EOLed for a while

---

connect-examples/v2/README.md
connect-examples/v2/csharp_checkout/README.md
connect-examples/v2/csharp_payment/README.md
connect-examples/v2/java_payment/README.md
connect-examples/v2/node_invoices/README.md
connect-examples/v2/node_orders-payments/README.md
connect-examples/v2/node_payment/README.md
connect-examples/v2/node_subscription/README.md
connect-examples/v2/php_checkout/README.md
connect-examples/v2/php_payment/README.md
connect-examples/v2/python_payment/README.md
connect-examples/v2/rails_payment/README.md

In order to create a bidirectional link between the apps and the SDK reference, we added a section for useful links at the beginning of each sample app, linking back to appropriate places in the documentation, based on both the development language and the APIs used in that particular sample app.

Add "Useful Links" section to each v2 example

---

connect-examples/v2/node_invoices/bin/script/seed-data.js
connect-examples/v2/node_invoices/package-lock.json
connect-examples/v2/node_invoices/package.json
connect-examples/v2/node_invoices/routes/invoice.js
connect-examples/v2/node_invoices/routes/management.js
connect-examples/v2/node_orders-payments/bin/script/seed-catalog.js
connect-examples/v2/node_orders-payments/package-lock.json
connect-examples/v2/node_orders-payments/package.json
connect-examples/v2/node_orders-payments/routes/checkout.js
connect-examples/v2/node_orders-payments/routes/index.js
connect-examples/v2/node_orders-payments/routes/order-confirmation.js
connect-examples/v2/node_payment/README.md
connect-examples/v2/node_payment/package-lock.json
connect-examples/v2/node_payment/package.json
connect-examples/v2/node_payment/routes/index.js

Some of the existing Node.js sample app use the `crypto` library to generate idempotency keys for API calls. However, this should be changed to the recommended key generation library according to the official Square documentation, which is `uuid`. For more information: https://developer.squareup.com/docs/working-with-apis/idempotency

Change idempotency key generation to official UUID library

---

connect-examples/v2/node_orders-payments/bin/script/sample-seed-data.json
connect-examples/v2/node_orders-payments/bin/script/seed-catalog.js

The seed script (which automatically creates catalog objects for the user before running the app), is using a data file which has `USD` hardcoded as the currency. This means that non-US users will not be able to run the seed script at all. I changed the seed script to use `main` as the locationID, and retrieve the actual currency from that. This requires no changes to documentation or .env file.

Fix hardcoded currency in seed script for node_orders_payments sample app

---

connect-examples/v2/java_catalog/README.md

Add `Useful Links` section to the migrated app.

Standardize java_catalog sample app README

---

connect-examples/v2/node_gift-cards/routes/gift-card.js
connect-examples/v2/node_gift-cards/routes/seed.js
connect-examples/v2/node_gift-cards/util/square-client.js

Since the `CreateCustomerCard` endpoint is now deprecated, the replacement is using the Cards API which is currently in Beta. This PR changes all usages of `createCustomerCard` and the deprecated card object (as part of the Customers API) to `createCard` and `listCards` as part of the [Cards API](https://developer.squareup.com/reference/square/cards/).

Update gift card sample to use Cards API

---

connect-examples/oauth/php/README.md

The readme for the OAuth PHP example has two paragraphs that repeat information in the paragraphs right before it. This removes them because they are unnecessary.

Delete repeated readme material

---

connect-examples/oauth/php/README.md
connect-examples/oauth/php/composer.json
connect-examples/oauth/php/request_token.php
connect-examples/v2/node_orders-payments/routes/checkout.js
connect-examples/v2/php_checkout/README.md
connect-examples/v2/php_checkout/checkout.php
connect-examples/v2/php_checkout/composer.json
connect-examples/v2/php_payment/README.md
connect-examples/v2/php_payment/composer.json
connect-examples/v2/php_payment/utils/location-info.php

Since we have some warning messages for the SDK when using php version >= 8.1, we want to restrict the sample apps to using old versions. This should be fixed around end of Feb.
This PR:
1. Restricts PHP version in the composer.json file.
2. Restricts PHP version in code.
3. Adds information to the README and removes some incosistencies.
4. Remove some references to sqpaymentform I've noticed.

Restrict PHP version to < 8.1

---

connect-examples/v2/java_payment/pom.xml

This updates Spring Boot to the latest version 2.6.6 in order to avoid a potential vulnerability (CVE-2022-22965).

chore: upgrade Spring Boot to 2.6.6 in the Java payments example

---

connect-examples/oauth/php/README.md
connect-examples/oauth/php/composer.json
connect-examples/oauth/php/request_token.php
connect-examples/v2/php_checkout/README.md
connect-examples/v2/php_checkout/checkout.php
connect-examples/v2/php_checkout/composer.json
connect-examples/v2/php_payment/README.md
connect-examples/v2/php_payment/composer.json
connect-examples/v2/php_payment/utils/location-info.php

Our newest release of the PHP SDK supports PHP version >= 8.1. I updated the PHP sample apps to not restrict the PHP version anymore.
Testing:
Manual testing.

Allow PHP version >= 8.1 on sample apps

---

connect-examples/v2/php_checkout/README.md
connect-examples/v2/php_payment/README.md
connect-examples/v2/php_payment/process-payment.php
connect-examples/v2/php_payment/utils/location-info.php

- Use the correct location id in php_payment as reported by Issue #327 
- Update README for php sample apps as reported by Issue #323

php_payment should use the correct location id

---

connect-examples/v2/node_subscription/routes/subscription.js

The current demo incorrectly shows the active subscriptions that a customer has subscribed to. 
For example, if Amelia subscribes to a Gym Membership plan, and then you view John Doe's subscription page and try to subscribe to the Gym Membership plan, you will see that is already marked as active when it should be inactive.
The problem occurs because the subscriptionsApi.searchSubscriptions() method has incorrect query parameters causing it to retrieve every subscription instead of the ones only owned by the customer.
Steps to reproduce error:
1. Click on Amelia
2. Click on Gym Membership Plan under Additional Plans
3. Click Subscribe
4. Go to John Doe
5. Click on Gym Membership Plan under Additional Plans
6. See that the Gym Membership Plan is already is active

fix subscription search query parameters

---

connect-examples/oauth/php/callback.php

One of the recent releases changed the `clientSecret` to be an optional parameter for `ObtainToken`. Our SDK passed the `clientSecret` directly to the model constructor, but that parameter is now removed. The new behaviour will set the parameter outside the constructor.

Fix oauth sample app obtainToken optional parameter

---

connect-examples/v2/csharp_payment/Pages/ProcessPayment.cshtml.cs
connect-examples/v2/csharp_payment/Pages/index.cshtml
connect-examples/v2/csharp_payment/Pages/index.cshtml.cs
connect-examples/v2/csharp_payment/wwwroot/js/sq-payment-flow.js
connect-examples/v2/java_payment/pom.xml
connect-examples/v2/java_payment/src/main/java/com/squareup/connectexamples/ecommerce/Main.java
connect-examples/v2/java_payment/src/main/java/com/squareup/connectexamples/ecommerce/TokenWrapper.java
connect-examples/v2/java_payment/src/main/resources/static/js/sq-payment-flow.js
connect-examples/v2/java_payment/src/main/resources/templates/index.html
connect-examples/v2/node_payment/package-lock.json
connect-examples/v2/node_payment/public/js/sq-payment-flow.js
connect-examples/v2/node_payment/routes/index.js
connect-examples/v2/node_payment/views/index.pug
connect-examples/v2/php_payment/README.md
connect-examples/v2/php_payment/index.php
connect-examples/v2/php_payment/process-payment.php
connect-examples/v2/php_payment/public/js/sq-payment-flow.js
connect-examples/v2/python_payment/README.md
connect-examples/v2/python_payment/main.py
connect-examples/v2/python_payment/static/js/sq-payment-flow.js
connect-examples/v2/rails_payment/app/assets/javascripts/sq-payment-flow.js
connect-examples/v2/rails_payment/app/controllers/payments_controller.rb
connect-examples/v2/rails_payment/app/controllers/welcome_controller.rb
connect-examples/v2/rails_payment/app/views/welcome/index.html.erb

Previously, we would generate a new idempotency key for each payment. This is bad practice, since the reason we use idempotency key in the first place is to prevent issues like multiple clicks or accidentally submitting multiple payment requests. I fixed the sample apps so that we generate the idempotency key on page load. 
**Previous behaviour:** loading the app and paying multiple times would "charge" the user multiple times since different idempotency keys are used for every request.
**New behaviour**: loading the app and paying multiple times would still generate multiple requests, but with the same idempotency key. Only the first payment will be successful.
Additionally, I fixed an issue with the Java payment app which wasn't working properly, and added some additional error handling …

Fix Payment SDK sample apps idempotency

---

connect-examples/v2/node_gift-cards/package-lock.json
connect-examples/v2/node_orders-payments/package-lock.json

Some sample apps had references to square artifactory in their lock files. This would prevent users from running npm install in the app directory as they will be unable to find the private artifactory. I removed the node modules and regenerated the lock files for those apps.
Testing:
Ran apps locally

Remove square artifactory references

---

connect-examples/v2/node_invoices/README.md
connect-examples/v2/node_invoices/bin/script/seed-data.js
connect-examples/v2/node_invoices/package-lock.json
connect-examples/v2/node_invoices/package.json
connect-examples/v2/node_invoices/routes/invoice.js
connect-examples/v2/node_invoices/util/square-client.js

This PR updates the invoice sample app and fixes a few issues:
1. Minimum node version is now V14.15.0.
2. The sample app is now using the latest SDK version.
3. Replace deprecated methods such as `createCustomerCard` and replace them with up-to-date ones (`createCard`).
4. Since cards are not part of the customer object anymore, use `ListCards` with customer ID to fetch cards associated with a certain customer.
5. Add error handling/retry for cases where the invoice to create contains unsupported/premium features according to this migration guide: https://developer.squareup.com/docs/invoices-api/overview#migration-notes
6. Fix README.

Update invoice sample app
